blank_issues_enabled: false
contact_links:
  - name: Lime3DS Discord
    url: https://discord.com/invite/4ZjMpAp3M6
    about: If you are experiencing an issue with Lime3DS and you need support, or if you have a general question, try asking in the official Lime3DS Discord linked here. Piracy is not allowed.
